name: Build and Deploy Java Microservice

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
    

      - name: Build with Mavens
        run: echo ${{github.workspace}}; cd ${{github.workspace}}/account-service ; mvn clean install

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run:  cd ${{github.workspace}}/account-service; docker build -t accounts-service .

      - name: Log in to Docker registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}


      - name: Tagging the image
        run: docker tag account-service ${{secrets.DOCKER_USERNAME}}/account-service:${{github.run_id}}

      - name: Push Docker image
        run: docker push ${{secrets.DOCKER_USERNAME}}/account-service:${{github.run_id}}
  